import t,{createContext as n,useState as r,useEffect as e,useContext as s}from"react";
/*! *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */var u,o=function(){return(o=Object.assign||function(t){for(var n,r=1,e=arguments.length;r<e;r++)for(var s in n=arguments[r])Object.prototype.hasOwnProperty.call(n,s)&&(t[s]=n[s]);return t}).apply(this,arguments)},i={},a=function(t){return i[t]},c={},f=function(t){return c[t]},b={status:"ready"},l=n(b),v=function(n){var s=n.children,o=r(b.status),v=o[0],y=o[1];return e((function(){Object.keys(i).forEach((function(t){a(t).subscribe((function(t){u===t&&(u="next_status"),y(u=t)}))}))}),[]),e((function(){Object.keys(c).forEach((function(t){var n=f(t);"ready"!==n.status&&y(n.status)}))}),[]),t.createElement(l.Provider,{value:{status:v}},s)},y=function(){function t(){this.observers=[]}return t.prototype.subscribe=function(t){this.observers.push(t)},t.prototype.unsubbscribe=function(t){this.observers=this.observers.filter((function(n){return n!==t}))},t.prototype.notify=function(t){this.observers.forEach((function(n){return n(t)}))},t}(),h=function(){function t(){var t,n,r;this.status="ready",this.key="_"+Math.random().toString(36).substr(2,9),t=this.key,n=new y,i=o(o({},i),((r={})[t]=n,r))}return t.prototype.setClass=function(t){var n=t;this.singletonClass=n},t.prototype.getProps=function(){return{singleton:this.singletonClass,status:this.status,key:this.key}},t}();function p(){var t=new h;return{watch:function(n){var r=a(t.key);t.status="in_progress",r.notify(t.status),n((function(){setTimeout((function(){t.status="ready",r.notify(t.status)}),0)}))},setClass:function(n){var r,e,s;t.setClass(n),r=n.name,e=t,c=o(o({},c),((s={})[r]=e,s))}}}function g(t){s(l);var n=function(t){var n=t.name,r=f(n);if(!r)throw new Error(n+" singleton was not correctly initialized or doesn't exist! Please, create your Singleton using createSingleton()'s setValue.");var e=r.getProps(),s=e.singleton,u=e.status,o=e.key;return{singleton:s,status:u,observable:a(o)}}(t);return{status:n.status,statusObservable:n.observable}}function d(t){return g(t).status}function m(t){d(t)}function k(t,n){void 0===n&&(n=500);var s=function(t){return g(t).statusObservable}(t),u=r(!1),o=u[0],i=u[1],a=function(t,n){var s=r(t),u=s[0],o=s[1];return e((function(){var r=setTimeout((function(){o(t)}),n);return function(){clearTimeout(r)}}),[t,n]),u}(o,n);return e((function(){var t=function(n){"ready"===n&&(i(!0),s.unsubbscribe(t))};return s.subscribe(t),function(){s.unsubbscribe(t)}}),[]),a}function w(n,r){return function(e){return m(r),t.createElement(n,o({},e))}}export{v as SingletonProvider,p as createSingleton,m as useReRenderOnUpdate,d as useSingletonStatus,k as useWasDataUpdated,w as withSingleton};
