# Workflow for CI.

name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0
      # Need to find a way for local tests
      # - name: Install Client Dependencies
      #   run: yarn
      # - name: Tests
      #   run: yarn test:ci
